// src/routes/tags/+page.svelte
<script lang="ts">
	import Tag from '$lib/components/Tag.svelte';
	import siteMetadata from '$lib/config/siteMetadata';

	let { data } = $props();

	const sortedTags = Object.entries(data.tagCounts).sort(([, a], [, b]) => b - a);
</script>

<svelte:head>
	<title>Tags | {siteMetadata.title}</title>
</svelte:head>

<div class="flex flex-col items-start justify-start divide-y divide-gray-200 dark:divide-gray-700 md:mt-24 md:flex-row md:items-center md:justify-center md:space-x-6 md:divide-y-0">
	<div class="space-x-2 pb-8 pt-6 md:space-y-5">
		<h1 class="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:border-r-2 md:px-6 md:text-6xl md:leading-14">
			Tags
		</h1>
	</div>
	<div class="flex max-w-lg flex-wrap">
		{#each sortedTags as [tag, count]}
			<div class="mb-2 mr-5 mt-2">
				<Tag text={tag} />
				<a href="/tags/{tag}" class="-ml-2 text-sm font-semibold uppercase text-gray-600 dark:text-gray-300" aria-label="View posts tagged {tag}">
					({count})
				</a>
			</div>
		{/each}
	</div>
</div>

// app/tags/page.tsx
import Link from '@/components/mdxComponents/Link'
import Tag from '@/components/Tag'
import { slug } from 'github-slugger'
import tagData from 'app/tag-data.json'
import { genPageMetadata } from 'app/seo'

export const metadata = genPageMetadata({ title: 'Tags', description: 'Things I blog about' })

export default async function Page() {
  const tagCounts = tagData as Record<string, number>
  const tagKeys = Object.keys(tagCounts)
  const sortedTags = tagKeys.sort((a, b) => tagCounts[b] - tagCounts[a])
  return (
    <>
      <div className="flex flex-col items-start justify-start divide-y divide-gray-200 dark:divide-gray-700 md:mt-24 md:flex-row md:items-center md:justify-center md:space-x-6 md:divide-y-0">
        <div className="space-x-2 pb-8 pt-6 md:space-y-5">
          <h1 className="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:border-r-2 md:px-6 md:text-6xl md:leading-14">
            Tags
          </h1>
        </div>
        <div className="flex max-w-lg flex-wrap">
          {tagKeys.length === 0 && 'No tags found.'}
          {sortedTags.map((t) => {
            return (
              <div key={t} className="mb-2 mr-5 mt-2">
                <Tag text={t} />
                <Link
                  href={`/tags/${slug(t)}`}
                  className="-ml-2 text-sm font-semibold uppercase text-gray-600 dark:text-gray-300"
                  aria-label={`View posts tagged ${t}`}
                >
                  {` (${tagCounts[t]})`}
                </Link>
              </div>
            )
          })}
        </div>
      </div>
    </>
  )
}
