// src/lib/components/Header.svelte
<script lang="ts">
	import siteMetadata from '$lib/config/siteMetadata';
	import headerNavLinks from '$lib/config/headerNavLinks';
	import ThemeSwitch from './ThemeSwitch.svelte';
	import MobileNav from './MobileNav.svelte';
</script>

<header class="flex items-center justify-between py-10">
	<div>
		<a href="/" aria-label={siteMetadata.headerTitle}>
			<div class="flex items-center justify-between">
				<div class="hidden h-6 text-2xl font-semibold sm:block">
					{siteMetadata.headerTitle}
				</div>
			</div>
		</a>
	</div>
	<div class="flex items-center space-x-4 leading-5 sm:space-x-6">
		{#each headerNavLinks.filter((link) => link.href !== '/') as link}
			<a
				href={link.href}
				class="hidden font-medium text-gray-900 dark:text-gray-100 sm:block"
			>
				{link.title}
			</a>
		{/each}
		<ThemeSwitch />
		<MobileNav />
	</div>
</header>

// components/Header.tsx
import siteMetadata from '@/content/siteMetadata'
import headerNavLinks from '@/content/headerNavLinks'
import Logo from '@/content/logo.svg'
import Link from './Link'
import MobileNav from './MobileNav'
import ThemeSwitch from './ThemeSwitch'
import SearchButton from './SearchButton'

const Header = () => {
  return (
    <header className="flex items-center justify-between py-10">
      <div>
        <Link href="/" aria-label={siteMetadata.headerTitle}>
          <div className="flex items-center justify-between">
            <div className="mr-3">
              <Logo />
            </div>
            {typeof siteMetadata.headerTitle === 'string' ? (
              <div className="hidden h-6 text-2xl font-semibold sm:block">
                {siteMetadata.headerTitle}
              </div>
            ) : (
              siteMetadata.headerTitle
            )}
          </div>
        </Link>
      </div>
      <div className="flex items-center space-x-4 leading-5 sm:space-x-6">
        {headerNavLinks
          .filter((link) => link.href !== '/')
          .map((link) => (
            <Link
              key={link.title}
              href={link.href}
              className="hidden font-medium text-gray-900 dark:text-gray-100 sm:block"
            >
              {link.title}
            </Link>
          ))}
        <SearchButton />
        <ThemeSwitch />
        <MobileNav />
      </div>
    </header>
  )
}

export default Header
