// components/mdxComponents/Note.tsx
import { ReactNode } from 'react'

interface Props {
  children: ReactNode
  className: string
}

const Note = ({ children, className }: Props) => {
  return (
    <div className={'grid place-content-center'}>
      <div className={'rounded bg-gray-100 dark:bg-gray-800' + (className ?? '')}>
        <div className={'box-content px-3 py-0'}>{children}</div>
      </div>
    </div>
  )
}

export default Note

// src/lib/components/Note.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	let { children, class: className = '' }: { children: Snippet; class?: string } = $props();
</script>

<div class="grid place-content-center">
	<div class="rounded bg-gray-100 dark:bg-gray-800 {className}">
		<div class="box-content px-3 py-0">
			{@render children()}
		</div>
	</div>
</div>
