// components/Series.tsx
import { SeriesInfo } from 'app/blog/[...slug]/page'
import { useRouter } from 'next/router'
interface Props {
  series?: SeriesInfo
  currSlug: string
}
const Series = ({ series, currSlug }: Props) => {
  const router = useRouter()
  if (!series) {
    return null
  }

  const { title, posts } = series

  return (
    <div className="pb-2">
      <p>This article is part of the {title} series.</p>
      <select
        defaultValue={`/blog/${currSlug}`}
        onChange={(e) => router.push(e.target.value)}
        className="block w-3/12 rounded-md border border-gray-300 bg-white px-4 py-2 text-gray-900 focus:border-primary-500 focus:ring-primary-500 dark:border-gray-900 dark:bg-gray-800 dark:text-gray-100"
      >
        {posts.map((p) => (
          <option key={p.title} value={`/blog/${p.slug}`}>
            {p.seriesTitle ?? p.title}
          </option>
        ))}
      </select>
    </div>
  )
}

export default Series

// src/lib/components/Series.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import type { SeriesInfo } from '$lib/utils/posts';

	let { series, currSlug }: { series: SeriesInfo | null; currSlug: string } = $props();

	function onChange(e: Event) {
		const target = e.target as HTMLSelectElement;
		goto(target.value);
	}
</script>

{#if series && series.posts.length > 1}
	<div class="pb-2">
		<p>This article is part of the {series.title} series.</p>
		<select
			value="/blog/{currSlug}"
			onchange={onChange}
			class="block w-3/12 rounded-md border border-gray-300 bg-white px-4 py-2 text-gray-900 focus:border-primary-500 focus:ring-primary-500 dark:border-gray-900 dark:bg-gray-800 dark:text-gray-100"
		>
			{#each series.posts as p}
				<option value="/blog/{p.metadata.slug}">
					{p.metadata.seriesTitle ?? p.metadata.title}
				</option>
			{/each}
		</select>
	</div>
{/if}
