// components/mdxComponents/TOCInline.tsx
import { Toc } from 'types/Toc';

interface TOCInlineProps {
  toc: Toc;
  indentDepth?: number;
  fromHeading?: number;
  toHeading?: number;
  asDisclosure?: boolean;
  exclude?: string | string[];
}

/**
 * Generates an inline table of contents
 * Exclude titles matching this string (new RegExp('^(' + string + ')$', 'i')).
 * If an array is passed the array gets joined with a pipe (new RegExp('^(' + array.join('|') + ')$', 'i')).
 *
 * @param {TOCInlineProps} {
 *   toc,
 *   indentDepth = 3,
 *   fromHeading = 1,
 *   toHeading = 6,
 *   asDisclosure = false,
 *   exclude = '',
 * }
 *
 */
const TOCInline = ({
  toc,
  indentDepth = 3,
  fromHeading = 1,
  toHeading = 6,
  asDisclosure = false,
  exclude = '',
}: TOCInlineProps) => {
  const re = Array.isArray(exclude)
    ? new RegExp('^(' + exclude.join('|') + ')$', 'i')
    : new RegExp('^(' + exclude + ')$', 'i');

  const filteredToc = toc.filter(
    (heading) =>
      heading.depth >= fromHeading && heading.depth <= toHeading && !re.test(heading.value)
  );

  const tocList = (
    <ul>
      {filteredToc.map((heading) => (
        <li key={heading.value} className={`${heading.depth >= indentDepth && 'ml-6'}`}>
          <a href={heading.url}>{heading.value}</a>
        </li>
      ))}
    </ul>
  );

  return (
    <>
      {asDisclosure ? (
        <details open>
          <summary className="pt-2 pb-2 ml-6 text-xl font-bold">Table of Contents</summary>
          <div className="ml-6">{tocList}</div>
        </details>
      ) : (
        tocList
      )}
    </>
  );
};

export default TOCInline;

// src/lib/components/TOCInline.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	interface Props {
		asDisclosure?: boolean;
		collapse?: boolean;
		fromHeading?: number;
		toHeading?: number;
		exclude?: string | string[];
		// Accept toc prop for backwards compatibility with old markdown syntax, but ignore it
		toc?: unknown;
	}

	let {
		asDisclosure = false,
		collapse = false,
		fromHeading = 1,
		toHeading = 4,
		exclude = '',
	}: Props = $props();

	interface TocEntry {
		url: string;
		title: string;
		depth: number;
	}

	let headings = $state<TocEntry[]>([]);

	onMount(() => {
		const re = Array.isArray(exclude)
			? new RegExp('^(' + exclude.join('|') + ')$', 'i')
			: exclude
				? new RegExp('^(' + exclude + ')$', 'i')
				: null;

		const selectors = [];
		for (let i = fromHeading; i <= toHeading; i++) {
			selectors.push(`h${i}[id]`);
		}

		const elements = document.querySelectorAll(selectors.join(', '));
		const result: TocEntry[] = [];

		elements.forEach((el) => {
			const title = el.textContent?.trim() || '';
			if (re && re.test(title)) return;
			const depth = parseInt(el.tagName[1]);
			result.push({
				url: `#${el.id}`,
				title,
				depth,
			});
		});

		headings = result;
	});
</script>

{#if headings.length > 0}
	{#if asDisclosure}
		<details open={!collapse}>
			<summary class="ml-6 pb-2 pt-2 text-xl font-bold">Table of Contents</summary>
			<div class="ml-6">
				<ul>
					{#each headings as heading}
						<li style="margin-left: {(heading.depth - fromHeading) * 1}rem">
							<a href={heading.url}>{heading.title}</a>
						</li>
					{/each}
				</ul>
			</div>
		</details>
	{:else}
		<ul>
			{#each headings as heading}
				<li style="margin-left: {(heading.depth - fromHeading) * 1}rem">
					<a href={heading.url}>{heading.title}</a>
				</li>
			{/each}
		</ul>
	{/if}
{/if}
